### ISSUE TITLE
How exactly does LoLNotes work?

### ISSUE THREAD

**Issue by meetshawn** [bladecoding/LoLNotes#62]
I understand it proxies the connection for the LoL client and parses the data like a MITM attack. How does it force the client to use the proxy without setting a global Windows proxy? Just looking briefly at the code does it really inject into the process or modify the memory to achieve this? Is this a hack of the Adobe Air client, or specific to the LoL client?

**Comment by NitroXenon** [comment]
Inject LoLNotes into LoLClient to capture the packets.
